### ISSUE TITLE
Checking types

### ISSUE THREAD

**Issue by dcjones** [UWSEDS/homework-2-python-functions-and-modules-gtalpey#1]
This test checks that every column has the same dtype, but should check that values within each column have the same python type (obtained with `type(x)`).

```python
    elif len(set(df.dtypes)) != 1:
        a = False
```

**Comment by gtalpey** [comment]
Hi Daniel, I just noticed the issue here on homework 2. I have updated my test to check the data types of each value for each column.

**Comment by dcjones** [comment]
Looks good. 7/7 points
